project_id = "witlybnacshxlidkptwt"

[functions.generate-results]
verify_jwt = false

[functions.generate-backlog]
verify_jwt = false

[functions.transform-questions]
verify_jwt = false

[functions.generate-variants]
verify_jwt = false
